### ISSUE TITLE
training scripts

### ISSUE THREAD

**Issue by jingwu6** [mlvlab/ProMetaR#2]
Thanks for sharing the code.

In the base2new_test.sh, shall we change

`DATASET.SUBSAMPLE_CLASSES ${SUB} `
to
`DATASET.SUBSAMPLE_CLASSES new `?

Or an error will incur

**Comment by PJin0** [comment]
Thank you for your interest in our paper!

To generate inference results for new classes, please run the following command:
`bash scripts/prometar/base2new_test.sh eurosat 1 0 new`

Let me know if you have any further questions.
Thanks.

**Comment by jingwu6** [comment]
I appreciate the authors' response. Could you please kindly direct me to where the soft prompt for the vision branch is implemented? I was able to locate the soft prompt for the text branch but couldn't find the one for the vision branch. Thank you again!
